# Stage 1: Build stage
FROM python:3.8 AS builder

WORKDIR /app

COPY calculator.py .

# Stage 2: Production stage
FROM python:3.8-slim

WORKDIR /app

# Copy only the necessary files from the builder stage
COPY --from=builder /app/calculator.py .

CMD ["python", "calculator.py"]
